[tool.poetry]
name = "libB"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pytest = "*"
setuptools = "*"

# Our sample external dependency
Flask = ">=1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
